'use client';

import { FormEvent, useState, useTransition } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, CircleGauge, Plus, RefreshCw, Scale, Target, Wallet } from 'lucide-react';
import Badge from '@/components/ui/Badge';
import Button from '@/components/ui/Button';
import { useToast } from '@/components/ui/ToastProvider';
import { getBudgetOverview, saveCostCenterBudget } from './actions';

type Data = Awaited<ReturnType<typeof getBudgetOverview>>;
type Company = { id: string; name: string; code: string };
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const months = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'];
const years = [new Date().getFullYear() - 1, new Date().getFullYear(), new Date().getFullYear() + 1];
const inputClass = 'w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-xs text-white focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/30';
const labelClass = 'mb-1.5 block text-[11px] font-bold text-slate-300';

export default function BudgetClient({ companies, initialData, initialYear }: { companies: Company[]; initialData: Data; initialYear: number }) {
  const toast = useToast();
  const [data, setData] = useState(initialData);
  const [companyId, setCompanyId] = useState('ALL');
  const [year, setYear] = useState(initialYear);
  const [showForm, setShowForm] = useState(false);
  const [isPending, startTransition] = useTransition();
  const load = (nextCompany = companyId, nextYear = year) => startTransition(async () => { try { setData(await getBudgetOverview({ company_id: nextCompany, year: nextYear })); } catch (error) { toast.error(error instanceof Error ? error.message : 'Falha ao carregar orçamentos.'); } });
  const chooseCompany = (value: string) => { setCompanyId(value); setShowForm(false); load(value, year); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { try { await saveCostCenterBudget({ company_id: companyId, cost_center_id: form.get('cost_center_id'), category_id: form.get('category_id'), year, month: Number(form.get('month')), planned_amount: Number(form.get('planned_amount')) }); toast.success('Orçamento mensal salvo.'); setShowForm(false); load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Falha ao salvar orçamento.'); } }); };
  const max = Math.max(1, ...data.monthly.flatMap((month) => [month.planned, month.actual]));

  return <div className="space-y-6 animate-fade-in">
    <section className="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-950 via-amber-950/30 to-slate-950 p-6 shadow-2xl"><Link href="/finance" className="inline-flex items-center gap-1 text-xs text-slate-400 hover:text-white"><ArrowLeft className="h-3.5 w-3.5" /> Financeiro</Link><div className="mt-4 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-amber-400">Planejamento orçamentário</p><h1 className="mt-2 text-3xl font-black text-white">Orçamento por Centro de Custo</h1><p className="mt-1 text-sm text-slate-400">Compare valores planejados e despesas realizadas por competência.</p></div><div className="flex gap-2"><select value={companyId} onChange={(event) => chooseCompany(event.target.value)} className={inputClass}><option value="ALL">Todas as empresas</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select><select value={year} onChange={(event) => { const value = Number(event.target.value); setYear(value); load(companyId, value); }} className={inputClass}>{years.map((item) => <option key={item}>{item}</option>)}</select><button onClick={() => load()} className="rounded-xl border border-slate-700 bg-slate-900 p-2.5 text-amber-300"><RefreshCw className={`h-4 w-4 ${isPending ? 'animate-spin' : ''}`} /></button></div></div></section>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi title="Orçamento anual" value={data.totals.planned} icon={Target} tone="text-blue-400" /><Kpi title="Realizado alocado" value={data.totals.actual} icon={Wallet} tone="text-rose-400" /><Kpi title="Saldo disponível" value={data.totals.available} icon={Scale} tone={data.totals.available >= 0 ? 'text-emerald-400' : 'text-rose-400'} /><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><p className="text-xs text-slate-400">Alertas</p><div className="mt-3 flex gap-3"><Badge variant="critical">{data.totals.exceeded} estourados</Badge><Badge variant="review">{data.totals.warning} atenção</Badge></div></div></div>

    {data.totals.unallocated > 0 && <div className="flex items-center gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-xs text-amber-200"><AlertTriangle className="h-5 w-5 shrink-0" /><span><b>{money.format(data.totals.unallocated)}</b> em despesas realizadas ainda não possuem centro de custo e não entram na comparação.</span></div>}

    <div className="flex justify-end"><Button disabled={companyId === 'ALL'} leftIcon={<Plus className="h-4 w-4" />} onClick={() => setShowForm((value) => !value)}>{companyId === 'ALL' ? 'Selecione uma empresa' : showForm ? 'Fechar formulário' : 'Definir orçamento'}</Button></div>
    {showForm && data.setup && <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 className="font-bold text-white">Orçamento mensal</h2>{(!data.setup.costCenters.length || !data.setup.categories.length) && <p className="mt-3 rounded-xl bg-amber-500/10 p-3 text-xs text-amber-200">Cadastre centros de custo e categorias de despesa em Administração.</p>}<form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label><span className={labelClass}>Centro de custo</span><select name="cost_center_id" required className={inputClass}><option value="">Selecione</option>{data.setup.costCenters.map((center) => <option key={center.id} value={center.id}>{center.code} — {center.name}</option>)}</select></label><label><span className={labelClass}>Categoria</span><select name="category_id" required className={inputClass}><option value="">Selecione</option>{data.setup.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span className={labelClass}>Mês</span><select name="month" required className={inputClass}>{months.map((month, index) => <option key={month} value={index + 1}>{month}</option>)}</select></label><label><span className={labelClass}>Valor planejado</span><input name="planned_amount" type="number" min="0" step="0.01" required className={inputClass} /></label><div className="md:col-span-2 xl:col-span-4"><Button type="submit" isLoading={isPending}>Salvar orçamento</Button></div></form></section>}

    <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold text-white">Planejado × realizado por mês</h2><div className="mt-6 grid h-64 grid-cols-12 items-end gap-2 border-b border-slate-700 pb-8">{data.monthly.map((month) => <div key={month.month} className="relative flex h-full items-end justify-center gap-1"><div className="w-3 rounded-t bg-blue-500/60" style={{ height: `${Math.max(2, month.planned / max * 100)}%` }} title={`Planejado: ${money.format(month.planned)}`} /><div className="w-3 rounded-t bg-rose-400" style={{ height: `${Math.max(2, month.actual / max * 100)}%` }} title={`Realizado: ${money.format(month.actual)}`} /><span className="absolute -bottom-6 text-[10px] text-slate-500">{month.label}</span></div>)}</div><div className="mt-5 flex gap-5 text-[11px]"><span className="text-blue-400">■ Planejado</span><span className="text-rose-400">■ Realizado</span></div></section>

    <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-xs"><thead className="bg-slate-950 text-slate-400"><tr>{['Mês','Empresa','Centro de custo','Categoria','Planejado','Realizado','Disponível','Consumo','Situação'].map((title) => <th key={title} className="p-4 text-left">{title}</th>)}</tr></thead><tbody>{data.rows.map((row) => <tr key={row.key} className="border-t border-slate-800"><td className="p-4 text-white">{months[row.month - 1]}</td><td className="p-4 text-slate-400">{row.company}</td><td className="p-4 font-bold text-white">{row.costCenter}</td><td className="p-4 text-slate-300">{row.category}</td><td className="p-4">{money.format(row.planned)}</td><td className="p-4 text-rose-400">{money.format(row.actual)}</td><td className={row.planned - row.actual >= 0 ? 'p-4 text-emerald-400' : 'p-4 text-rose-400'}>{money.format(row.planned - row.actual)}</td><td className="p-4"><div className="w-28"><p className="mb-1 text-right">{row.usage >= 999 ? 'Sem orçamento' : `${row.usage.toFixed(1)}%`}</p><div className="h-1.5 rounded bg-slate-800"><div className={`h-1.5 rounded ${row.status === 'EXCEEDED' ? 'bg-rose-500' : row.status === 'WARNING' ? 'bg-amber-500' : 'bg-emerald-500'}`} style={{ width: `${Math.min(100, row.usage)}%` }} /></div></div></td><td className="p-4"><BudgetBadge status={row.status} /></td></tr>)}</tbody></table></div>{!data.rows.length && <div className="p-12 text-center text-sm text-slate-500">Nenhum orçamento ou despesa alocada encontrado para o período.</div>}</section>
  </div>;
}

function Kpi({ title, value, icon: Icon, tone }: { title: string; value: number; icon: typeof CircleGauge; tone: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex justify-between"><p className="text-xs text-slate-400">{title}</p><Icon className={`h-5 w-5 ${tone}`} /></div><p className={`mt-2 text-2xl font-black ${tone}`}>{money.format(value)}</p></div>; }
function BudgetBadge({ status }: { status: string }) { return status === 'EXCEEDED' ? <Badge variant="critical">Estourado</Badge> : status === 'WARNING' ? <Badge variant="review">Atenção</Badge> : <Badge variant="active">Saudável</Badge>; }
