'use server';
import { z } from 'zod';
import { prisma } from '@/lib/db';
import { getAuthorizedCompanyScope } from '@/lib/auth';
const Schema = z.object({ company_id: z.string().uuid().or(z.literal('ALL')), year: z.number().int().min(2020).max(2100), cost_center_id: z.string().uuid().or(z.literal('ALL')).default('ALL') });
const labels = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
export async function getDre(input: unknown) { const data = Schema.parse(input); const { companyIds } = await getAuthorizedCompanyScope('view', data.company_id); const companyWhere = companyIds === null ? {} : { company_id: { in: companyIds } }; const end = new Date(`${data.year + 1}-01-01T00:00:00.000Z`); const previousStart = new Date(`${data.year - 1}-01-01T00:00:00.000Z`); const baseWhere = { ...companyWhere, scenario: 'ACTUAL' as const, deleted_at: null, is_internal_transfer: false, period_start: { gte: previousStart, lt: end } };
  const [directEntries, allocatedEntries, costCenters] = await Promise.all([
    prisma.financialEntry.findMany({ where: { ...baseWhere, ...(data.cost_center_id === 'ALL' ? {} : { cost_center_id: data.cost_center_id }) }, select: { period_start: true, nature: true, amount: true, category: { select: { dre_group: true } } } }),
    data.cost_center_id === 'ALL' ? Promise.resolve([]) : prisma.financialAllocation.findMany({ where: { ...companyWhere, cost_center_id: data.cost_center_id, financial_entry: baseWhere }, select: { allocated_amount: true, financial_entry: { select: { period_start: true, nature: true, category: { select: { dre_group: true } } } } } }),
    prisma.costCenter.findMany({ where: { ...companyWhere, is_active: true }, orderBy: { code: 'asc' }, select: { id: true, code: true, name: true } }),
  ]);
  const entries = data.cost_center_id === 'ALL' ? directEntries : [...directEntries, ...allocatedEntries.map((item) => ({ ...item.financial_entry, amount: item.allocated_amount }))];
  const aggregate = (year: number) => { const groups = new Map<string, number>(); const monthly = labels.map((label, index) => ({ month: index + 1, label, result: 0 })); for (const entry of entries) { if (entry.period_start.getUTCFullYear() !== year) continue; const signed = entry.nature === 'REVENUE' ? Number(entry.amount) : -Number(entry.amount); groups.set(entry.category.dre_group, (groups.get(entry.category.dre_group) || 0) + signed); monthly[entry.period_start.getUTCMonth()].result += signed; } return { groups, monthly }; };
  const current = aggregate(data.year); const previous = aggregate(data.year - 1); const value = (map: Map<string, number>, group: string) => map.get(group) || 0;
  const buildLines = (map: Map<string, number>) => { const gross = value(map,'GROSS_REVENUE'); const deductions = value(map,'REVENUE_DEDUCTION'); const netRevenue = gross + deductions; const direct = value(map,'DIRECT_COST'); const grossProfit = netRevenue + direct; const opex = value(map,'OPERATING_EXPENSE'); const operating = grossProfit + opex; const financial = value(map,'FINANCIAL_RESULT'); const taxes = value(map,'TAX'); return [{ key:'gross',label:'Receita bruta',value:gross,level:0 },{ key:'deductions',label:'(-) Deduções da receita',value:deductions,level:1 },{ key:'netRevenue',label:'Receita líquida',value:netRevenue,level:0,total:true },{ key:'direct',label:'(-) Custos diretos',value:direct,level:1 },{ key:'grossProfit',label:'Lucro bruto',value:grossProfit,level:0,total:true },{ key:'opex',label:'(-) Despesas operacionais',value:opex,level:1 },{ key:'operating',label:'Resultado operacional',value:operating,level:0,total:true },{ key:'financial',label:'Resultado financeiro',value:financial,level:1 },{ key:'taxes',label:'(-) Tributos sobre resultado',value:taxes,level:1 },{ key:'net',label:'Resultado líquido',value:operating+financial+taxes,level:0,total:true }]; };
  const currentLines = buildLines(current.groups); const previousMap = new Map(buildLines(previous.groups).map((line) => [line.key,line.value])); return { year:data.year, lines:currentLines.map((line)=>({ ...line, previous:previousMap.get(line.key)||0, variance:line.value-(previousMap.get(line.key)||0) })), monthly:current.monthly, costCenters };
}
