'use client';

import { FormEvent, useState, useTransition } from 'react';
import Link from 'next/link';
import { ArrowLeft, GitBranch, Play, Plus, RefreshCw, RotateCcw, WandSparkles } from 'lucide-react';
import Badge from '@/components/ui/Badge';
import Button from '@/components/ui/Button';
import { useToast } from '@/components/ui/ToastProvider';
import { applyAllocationRule, createAllocationRule, getAllocationOverview, rollbackAllocationRule, setAllocationRuleActive } from './actions';

type Data = Awaited<ReturnType<typeof getAllocationOverview>>;
type Company = { id: string; name: string; code: string };
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const inputClass = 'w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-xs text-white focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/30';
const labelClass = 'mb-1.5 block text-[11px] font-bold text-slate-300';

export default function AllocationClient({ companies, initialData }: { companies: Company[]; initialData: Data }) {
  const toast = useToast(); const [data, setData] = useState(initialData); const [companyId, setCompanyId] = useState('ALL'); const [showForm, setShowForm] = useState(false); const [isPending, startTransition] = useTransition();
  const load = (nextCompany = companyId) => startTransition(async () => { try { setData(await getAllocationOverview({ company_id: nextCompany })); } catch (error) { toast.error(error instanceof Error ? error.message : 'Falha ao carregar regras.'); } });
  const chooseCompany = (value: string) => { setCompanyId(value); setShowForm(false); load(value); };
  const run = (operation: () => Promise<unknown>, message: string) => startTransition(async () => { try { await operation(); toast.success(message); load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível concluir a operação.'); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const centers = form.getAll('cost_center_id').map(String); const percentages = form.getAll('percentage').map(Number); const items = centers.map((cost_center_id, index) => ({ cost_center_id, percentage: percentages[index] })).filter((item) => item.cost_center_id && item.percentage > 0); run(() => createAllocationRule({ company_id: companyId, name: form.get('name'), category_id: form.get('category_id') || null, account_contains: form.get('account_contains') || null, items }), 'Regra de rateio criada.'); setShowForm(false); };
  return <div className="space-y-6 animate-fade-in">
    <section className="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-950 via-violet-950/30 to-slate-950 p-6 shadow-2xl"><Link href="/finance" className="inline-flex items-center gap-1 text-xs text-slate-400 hover:text-white"><ArrowLeft className="h-3.5 w-3.5" /> Financeiro</Link><div className="mt-4 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-violet-400">Classificação inteligente</p><h1 className="mt-2 text-3xl font-black text-white">Regras de Rateio</h1><p className="mt-1 text-sm text-slate-400">Distribua despesas sem classificação entre centros de custo.</p></div><div className="flex gap-2"><select value={companyId} onChange={(event) => chooseCompany(event.target.value)} className={inputClass}><option value="ALL">Todas as empresas</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select><button onClick={() => load()} className="rounded-xl border border-slate-700 bg-slate-900 p-2.5 text-violet-300"><RefreshCw className={`h-4 w-4 ${isPending ? 'animate-spin' : ''}`} /></button></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Despesas sem rateio" value={String(data.totals.unallocatedCount)} /><Metric label="Valor sem rateio" value={money.format(data.totals.unallocatedAmount)} /><Metric label="Distribuições criadas" value={String(data.totals.allocationCount)} /><Metric label="Valor distribuído" value={money.format(data.totals.allocatedAmount)} /></div>
    <div className="flex justify-end"><Button disabled={companyId === 'ALL'} leftIcon={<Plus className="h-4 w-4" />} onClick={() => setShowForm((value) => !value)}>{companyId === 'ALL' ? 'Selecione uma empresa' : showForm ? 'Fechar formulário' : 'Nova regra de rateio'}</Button></div>
    {showForm && data.setup && <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 className="font-bold text-white">Nova regra</h2><p className="mt-1 text-xs text-slate-400">A categoria e o texto são combinados quando ambos forem informados. Os percentuais devem totalizar 100%.</p>{!data.setup.costCenters.length && <p className="mt-3 rounded-xl bg-amber-500/10 p-3 text-xs text-amber-200">Cadastre centros de custo em Administração antes de criar uma regra.</p>}<form onSubmit={submit} className="mt-5 space-y-5"><div className="grid gap-4 md:grid-cols-3"><label><span className={labelClass}>Nome da regra</span><input name="name" required minLength={3} className={inputClass} placeholder="Ex.: Rateio administrativo" /></label><label><span className={labelClass}>Categoria de despesa</span><select name="category_id" className={inputClass}><option value="">Qualquer categoria</option>{data.setup.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span className={labelClass}>Parceiro/conta contém</span><input name="account_contains" className={inputClass} placeholder="Ex.: AWS" /></label></div><div><p className={labelClass}>Destinos do rateio</p><div className="grid gap-3 md:grid-cols-3">{[0,1,2].map((index) => <div key={index} className="grid grid-cols-[1fr_90px] gap-2 rounded-xl border border-slate-800 bg-slate-950/50 p-3"><select name="cost_center_id" required={index === 0} className={inputClass}><option value="">Centro de custo</option>{data.setup!.costCenters.map((center) => <option key={center.id} value={center.id}>{center.code} — {center.name}</option>)}</select><input name="percentage" type="number" min="0" max="100" step="0.01" required={index === 0} className={inputClass} placeholder="%" /></div>)}</div></div><Button type="submit" isLoading={isPending}>Salvar regra</Button></form></section>}
    <section className="grid gap-4 xl:grid-cols-2">{data.rules.map((rule) => <div key={rule.id} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-white">{rule.name}</h2><p className="mt-1 text-xs text-slate-500">{rule.company.name}</p></div><button disabled={isPending} onClick={() => run(() => setAllocationRuleActive(rule.id, !rule.is_active), rule.is_active ? 'Regra desativada.' : 'Regra ativada.')}><Badge variant={rule.is_active ? 'active' : 'ghost'}>{rule.is_active ? 'Ativa' : 'Inativa'}</Badge></button></div><div className="mt-4 rounded-xl bg-slate-950/60 p-3 text-xs text-slate-300"><p><b>Categoria:</b> {rule.category?.name || 'Qualquer'}</p><p className="mt-1"><b>Texto:</b> {rule.account_contains || 'Não informado'}</p></div><div className="mt-4 space-y-2">{rule.items.map((item) => <div key={item.id} className="flex justify-between text-xs"><span className="text-slate-300">{item.cost_center.code} — {item.cost_center.name}</span><b className="text-violet-400">{item.percentage.toFixed(2)}%</b></div>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-2 border-t border-slate-800 pt-4"><span className="text-xs text-slate-500">{rule._count.allocations} distribuições aplicadas</span><div className="flex gap-2">{rule._count.allocations > 0 && <Button size="sm" variant="danger" leftIcon={<RotateCcw className="h-3.5 w-3.5" />} onClick={() => run(() => rollbackAllocationRule(rule.id), 'Rateios desta regra desfeitos.')} isLoading={isPending}>Desfazer</Button>}<Button size="sm" variant="secondary" disabled={!rule.is_active} leftIcon={<Play className="h-3.5 w-3.5" />} onClick={() => run(() => applyAllocationRule(rule.id), 'Regra aplicada aos lançamentos compatíveis.')} isLoading={isPending}>Aplicar</Button></div></div></div>)}{!data.rules.length && <div className="xl:col-span-2 rounded-2xl border border-dashed border-slate-700 p-12 text-center"><WandSparkles className="mx-auto h-8 w-8 text-violet-400" /><p className="mt-3 text-sm text-slate-400">Nenhuma regra de rateio cadastrada.</p></div>}</section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex justify-between"><p className="text-xs text-slate-400">{label}</p><GitBranch className="h-5 w-5 text-violet-400" /></div><p className="mt-2 text-2xl font-black text-white">{value}</p></div>; }
